// ajax calls
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// course actions
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

// author actions
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';

// rank actions
export const LOAD_RANKS_SUCCESS = 'LOAD_RANKS_SUCCESS';
export const LOAD_RANKS_FAILED = 'LOAD_RANKS_FAILED';
export const LOAD_RANK_SUCCESS = 'LOAD_RANK_SUCCESS';
export const LOAD_RANK_FAILED = 'LOAD_RANK_FAILED';
export const CREATE_RANK_SUCCESS = 'CREATE_RANK_SUCCESS';
export const CREATE_RANK_FAILED = 'CREATE_RANK_FAILED';
export const UPDATE_RANK_SUCCESS = 'UPDATE_RANK_SUCCESS';
export const UPDATE_RANK_FAILED = 'UPDATE_RANK_FAILED';
export const DELETE_RANK_SUCCESS = 'DELETE_RANK_SUCCESS';
export const DELETE_RANK_FAILED = 'DELETE_RANK_FAILED';

// phone actions
export const LOAD_PHONES_SUCCESS = 'LOAD_PHONES_SUCCESS';
export const LOAD_PHONES_FAILED = 'LOAD_PHONES_FAILED';
export const CREATE_PHONE_SUCCESS = 'CREATE_PHONE_SUCCESS';
export const CREATE_PHONE_FAILED = 'CREATE_PHONE_FAILED';
export const UPDATE_PHONE_SUCCESS = 'UPDATE_PHONE_SUCCESS';
export const UPDATE_PHONE_FAILED = 'UPDATE_PHONE_FAILED';

// student actions
export const LOAD_STUDENTS_SUCCESS = 'LOAD_STUDENTS_SUCCESS';
export const LOAD_STUDENTS_FAILED = 'LOAD_STUDENTS_FAILED';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_FAILED = 'CREATE_STUDENT_FAILED';
export const UPDATE_STUDENT_FAILED = 'UPDATE_STUDENT_FAILED';

// academy actions
export const LOAD_ACADEMIES_SUCCESS = 'LOAD_ACADEMIES_SUCCESS';
export const LOAD_ACADEMIES_FAILED = 'LOAD_ACADEMIES_FAILED';
export const LOAD_ACADEMY_SUCCESS = 'LOAD_ACADEMY_SUCCESS';
export const LOAD_ACADEMY_FAILED = 'LOAD_ACADEMY_FAILED';
export const CREATE_ACADEMY_SUCCESS = 'CREATE_ACADEMY_SUCCESS';
export const UPDATE_ACADEMY_SUCCESS = 'UPDATE_ACADEMY_SUCCESS';
export const CREATE_ACADEMY_FAILED = 'CREATE_ACADEMY_FAILED';
export const UPDATE_ACADEMY_FAILED = 'UPDATE_ACADEMY_FAILED';
export const DELETE_ACADEMY_SUCCESS = 'DELETE_ACADEMY_SUCCESS';
export const DELETE_ACADEMY_FAILED = 'DELETE_ACADEMY_FAILED';

// state actions
export const LOAD_STATES_SUCCESS = 'LOAD_STATES_SUCCESS';
export const LOAD_STATES_FAILED = 'LOAD_STATES_FAILED';

// address actions
export const LOAD_ADDRESSES_SUCCESS = 'LOAD_ADDRESSES_SUCCESS';
export const LOAD_ADDRESSES_FAILED = 'LOAD_ADDRESSES_FAILED';
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const CREATE_ADDRESS_FAILED = 'CREATE_ADDRESS_FAILED';
export const UPDATE_ADDRESS_FAILED = 'UPDATE_ADDRESS_FAILED';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAILED = 'DELETE_ADDRESS_FAILED';

// address actions
export const LOAD_ADDRESS_TYPES_SUCCESS = 'LOAD_ADDRESS_TYPES_SUCCESS';
export const LOAD_ADDRESS_TYPES_FAILED = 'LOAD_ADDRESS_TYPES_FAILED';
export const CREATE_ADDRESS_TYPE_SUCCESS = 'CREATE_ADDRESS_TYPE_SUCCESS';
export const UPDATE_ADDRESS_TYPE_SUCCESS = 'UPDATE_ADDRESS_TYPE_SUCCESS';
export const CREATE_ADDRESS_TYPE_FAILED = 'CREATE_ADDRESS_TYPE_FAILED';
export const UPDATE_ADDRESS_TYPE_FAILED = 'UPDATE_ADDRESS_TYPE_FAILED';
export const DELETE_ADDRESS_TYPE_SUCCESS = 'DELETE_ADDRESS_TYPE_SUCCESS';
export const DELETE_ADDRESS_TYPE_FAILED = 'DELETE_ADDRESS_TYPE_FAILED';

// student status actions
export const LOAD_STUDENT_STATUSES_SUCCESS = 'LOAD_STUDENT_STATUSES_SUCCESS';
export const LOAD_STUDENT_STATUSES_FAILED = 'LOAD_STUDENT_STATUSES_FAILED';
export const CREATE_STUDENT_STATUS_SUCCESS = 'CREATE_STUDENT_STATUS_SUCCESS';
export const UPDATE_STUDENT_STATUS_SUCCESS = 'UPDATE_STUDENT_STATUS_SUCCESS';
export const CREATE_STUDENT_STATUS_FAILED = 'CREATE_STUDENT_STATUS_FAILED';
export const UPDATE_STUDENT_STATUS_FAILED = 'UPDATE_STUDENT_STATUS_FAILED';
export const DELETE_STUDENT_STATUS_SUCCESS = 'DELETE_STUDENT_STATUS_SUCCESS';
export const DELETE_STUDENT_STATUS_FAILED = 'DELETE_STUDENT_STATUS_FAILED';

// state actions
export const LOAD_ACADEMYADDRESSES_SUCCESS = 'LOAD_ACADEMYADDRESSES_SUCCESS';
export const LOAD_ACADEMYADDRESSES_FAILED = 'LOAD_ACADEMYADDRESSES_FAILED';
