USE NextCARE
GO

/****** Object:  Table dbo.States    Script Date: 5/29/2018 6:54:08 PM ******/
IF OBJECT_ID('dbo.States', 'U') IS NOT NULL
BEGIN
  DROP TABLE dbo.States
END
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.States
(
  StatesId int IDENTITY(1,1) NOT NULL,
  StateName nvarchar(1024) NOT NULL,
  Abbreviation NVARCHAR(3) NOT NULL,
  CONSTRAINT PK_States PRIMARY KEY CLUSTERED
(
	StatesId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
