Use NextCARE;
go

BEGIN TRANSACTION
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('878 Ledgendary Pl', '', 4, 'Peters', 0, 27, '43256');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('638 Destin Cir', '', 2, 'Fort Walton', 1, 20, '65478');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('2034 US Hwy 98', '', 4, 'Irondale', 1, 41, '35778');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('878 Ledgendary Pl', '', 4, 'Irondale', 1, 42, '65478');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('234 Wearing Dr', '', 3, 'Trussville', 1, 49, '89988');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('12345 Collin Lane', '', 1, 'Big Town', 0, 13, '35442');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('878 Ledgendary Pl', '', 1, 'Sizzle', 1, 2, '72861');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('234 Wearing Dr', '', 1, 'Fort Walton', 0, 11, '74562');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('12345 Collin Lane', '', 1, 'Fort Walton', 1, 5, '25676');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('77 Parker st', '', 4, 'Big Town', 1, 11, '88887');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('554 Acher Place', 'Apt 21', 4, 'Irondale', 1, 44, '32009');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('900 Benning Way', '', 2, 'Sizzle', 0, 3, '88887');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('64923 Creekview Dr', '', 3, 'Panima', 1, 12, '98765');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('7654 Extra Long St', '', 1, 'Sizzle', 1, 1, '98765');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('900 Benning Way', '', 2, 'Trussville', 0, 18, '74562');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('123 Main St', '', 1, 'Sizzle', 1, 25, '74562');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('878 Ledgendary Pl', '', 3, 'Panima', 1, 18, '35442');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('64923 Creekview Dr', '', 3, 'Irondale', 1, 42, '89988');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('2034 US Hwy 98', '', 2, 'Trussville', 0, 8, '25676');
INSERT INTO Address (AddressLine1, AddressLine2, AddressTypeId, City, IsPrimary, StatesId, Zip) VALUES('7654 Extra Long St', '', 4, 'Oakaloosa', 1, 42, '98765');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('Capp', '4/19/1998 3:42:44 PM', 'Corey', 'Richardson', 'N', 6, '', 3, 'F', 'jjs2mtezGG5sGhliNCfq3A==', 'ddt/q3tb2ATszQ==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('Jimmy', '2/26/2014 3:42:44 PM', 'Steve', 'Baker', 'Q', 3, '', 4, 'F', 'G/dKXBZArt8SzwHIcJsIDw==', 'IbIKBJqzBG2Ijg==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('BillyBob', '2/1/2006 3:42:44 PM', 'Mark', 'Peterson', 'E', 7, '', 2, 'M', 'ER1xp6EwT2qrJM8aH9VPww==', 'IbIKBJqzBG2Ijg==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('', '6/9/1975 3:42:44 PM', 'Rita', 'Weeks', 'W', 6, '', 4, 'M', 'ZR03wyJX/YTP+W9NzxYGGA==', 'ddt/q3tb2ATszQ==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('Capp', '11/4/1974 3:42:44 PM', 'Mark', 'Bradshaw', 'S', 2, '', 2, 'F', 'jjs2mtezGG5sGhliNCfq3A==', 'NDcTubum+Hp0xA==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('', '5/26/1975 3:42:44 PM', 'Steve', 'Chen', 'H', 1, '', 1, 'M', '6YWkahPkLgff8qA20TfvTQ==', 'moRnQNqK5OdR3A==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('Capp', '12/26/1994 3:42:44 PM', 'Rita', 'Bradshaw', 'J', 2, '', 1, 'M', 'Ax6ZCLfl6YH99ybECLMlGw==', 'NDcTubum+Hp0xA==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('Beth', '10/11/2012 3:42:44 PM', 'Corey', 'Weeks', 'X', 6, '', 3, 'F', '8nDHFlEDmeNs1220GABsCg==', 'hZ9tdqTMW2s73Q==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('Liz', '10/12/1975 3:42:44 PM', 'Rita', 'Johnson', 'H', 7, '', 5, 'M', 'jjs2mtezGG5sGhliNCfq3A==', 'CZk2FA7QfWcX7A==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('', '7/29/2001 3:42:44 PM', 'Bob', 'Williamson', 'E', 3, '', 4, 'F', '8nDHFlEDmeNs1220GABsCg==', 'moRnQNqK5OdR3A==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('Joe', '10/2/1993 3:42:44 PM', 'Mary', 'Garcia', 'A', 1, '', 3, 'F', 'ZR03wyJX/YTP+W9NzxYGGA==', 'ddt/q3tb2ATszQ==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('Timmy', '8/17/1980 3:42:44 PM', 'Corey', 'Baker', 'N', 7, '', 3, 'M', 'ZR03wyJX/YTP+W9NzxYGGA==', 'ddt/q3tb2ATszQ==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('Capp', '1/5/1998 3:42:44 PM', 'Eric', 'Harmon', 'T', 4, '', 2, 'F', '3mhApdUEv55k/yBaChIZWQ==', 'NDcTubum+Hp0xA==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('', '3/28/1983 3:42:44 PM', 'Rita', 'Noyce', 'Q', 4, '', 3, 'M', 'G/dKXBZArt8SzwHIcJsIDw==', 'NDcTubum+Hp0xA==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('', '5/8/1991 3:42:44 PM', 'Bob', 'Harmon', 'N', 1, '', 3, 'F', '6YWkahPkLgff8qA20TfvTQ==', 'CZk2FA7QfWcX7A==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('Capp', '4/26/1978 3:42:44 PM', 'Matthew', 'Noyce', 'J', 1, '', 4, 'M', 'jjs2mtezGG5sGhliNCfq3A==', 'IbIKBJqzBG2Ijg==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('Liz', '5/18/1982 3:42:44 PM', 'Matthew', 'Almound', 'W', 2, '', 4, 'F', '8nDHFlEDmeNs1220GABsCg==', 'IbIKBJqzBG2Ijg==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('Beth', '3/24/2002 3:42:44 PM', 'Kelley', 'Peterson', 'S', 6, '', 3, 'F', 'ZR03wyJX/YTP+W9NzxYGGA==', 'hZ9tdqTMW2s73Q==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('BillyBob', '3/11/1975 3:42:44 PM', 'Steve', 'Baker', 'S', 3, '', 3, 'F', '6YWkahPkLgff8qA20TfvTQ==', 'ddt/q3tb2ATszQ==', '');
INSERT INTO Person (Alias, DateOfBirth, FirstName, LastName, MiddleName, PersonTypeId, Prefix, RaceId, Sex, SocialSecurityNumber, SSNSalt, Suffix) VALUES('Timmy', '10/10/2009 3:42:44 PM', 'Steve', 'Chen', 'Q', 3, '', 2, 'F', 'jjs2mtezGG5sGhliNCfq3A==', 'ddt/q3tb2ATszQ==', '');
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('seven.three@burgers.com', 1, 1);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('eight.ten@outlook.com', 1, 1);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('nine.three@mail.mine.com', 3, 1);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('seven.three@burgers.com', 3, 1);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('seven.three@burgers.com', 4, 1);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('four.three@email.net', 2, 1);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('nine.three@mail.mine.com', 2, 1);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('one.two@yahoo.com', 1, 1);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('four.three@email.net', 2, 0);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('eight.ten@outlook.com', 4, 1);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('two.seven@yahoo.com', 3, 0);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('two.ten@outlook.com', 4, 1);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('two.ten@outlook.com', 3, 1);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('eight.ten@outlook.com', 2, 1);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('eight.seven@outlook.com', 2, 1);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('eight.ten@outlook.com', 2, 1);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('one.two@yahoo.com', 4, 1);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('two.ten@outlook.com', 4, 1);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('seven.three@burgers.com', 4, 0);
INSERT INTO Email (EmailAddress, EmailTypeId, IsPrimary) VALUES('nine.liz@gmail.com', 4, 1);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('', 1, '7168784720', 3);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('', 1, '6719998765', 3);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('9000', 0, '5347869400', 3);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('', 1, '7168784720', 4);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('2345', 1, '3458762756', 1);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('', 1, '7168784720', 1);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('4567', 1, '8506671212', 4);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('2345', 0, '7452229999', 4);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('', 0, '7168784720', 3);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('2345', 1, '3458762756', 4);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('2345', 1, '8189872300', 2);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('4567', 1, '7748762987', 3);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('', 1, '6719998765', 4);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('2345', 1, '8505557654', 1);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('2345', 0, '7452229999', 3);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('', 1, '6719998765', 2);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('', 1, '2058889876', 3);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('7398', 0, '3247896543', 4);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('', 1, '2058889876', 4);
INSERT INTO Phone (Extension, IsPrimary, PhoneNumber, PhoneTypeId) VALUES('', 0, '8505557654', 3);


ROLLBACK TRANSACTION