USE [master]
GO

/****** Object:  Login [NT AUTHORITY\IUSR]    Script Date: 7/21/2018 4:31:35 PM ******/
CREATE LOGIN [NT AUTHORITY\IUSR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT AUTHORITY\IUSR]
GO
